---
# Source: hik8s-system/templates/secret.yaml
apiVersion: v1
data:
    auth0domain: ZGV2LXNrc2dueDFqcHFjdDZ5Z2kudXMuYXV0aDAuY29t
    clientid: YWJj
    clientsecret: YWJj
kind: Secret
metadata:
    name: hik8s-credentials
    namespace: hik8s-system
