---
# Source: hik8s-system/templates/secret.yaml
apiVersion: v1
data:
    auth0domain: abc
    clientid: abc
    clientsecret: abc
kind: Secret
metadata:
    name: hik8s-credentials
    namespace: hik8s-system
