---
# Source: hik8s/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchd
  namespace: hik8s-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: watchd
  template:
    metadata:
      labels:
        name: watchd
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: watchd
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop: ["ALL"]
        image: ghcr.io/hik8s/watchd:0.3.0
        imagePullPolicy: IfNotPresent
        env:
        - name: HIK8S_HOST
          value: api.hik8s.ai
        - name: RUST_LOG
          value: info
        - name: HIK8S_PORT
          value: "443"
        - name: AUTH_AUDIENCE
          value: api.hik8s.ai,data-intake
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: hik8s-credentials
              key: clientid
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: hik8s-credentials
              key: clientsecret
        - name: AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: hik8s-credentials
              key: authdomain
      serviceAccountName: api-viewer
