# Default values

dataIntake:
  endpoint: api.hik8s.ai
  port: 443

auth:
  createSecret: true
  audience: "api.hik8s.ai,data-intake"
  credentials:
    clientId: ""
    clientSecret: ""
    domain: ""
  secretKeys:
    clientId: clientid
    clientSecret: clientsecret
    domain: authdomain
  secretName: hik8s-credentials

image:
  registry: ghcr.io/hik8s
  pullPolicy: IfNotPresent

watchd:
  imageVersion: 0.3.0
  logLevel: info
  nodeSelector: {}
  rbac:
    serviceAccountName: api-viewer
    clusterRoleName: api-viewer
    clusterRoleBindingName: api-viewer
    suffix: ""


logd:
  imageVersion: 0.3.0
  logLevel: info
  nodeSelector: {}
