{{- if eq (toString .Values.auth.createSecret) "true" }}
apiVersion: v1
data:
    {{ .Values.auth.secretKeys.domain }}: {{ .Values.auth.credentials.domain | b64enc }}
    {{ .Values.auth.secretKeys.clientId }}: {{ .Values.auth.credentials.clientId | b64enc }}
    {{ .Values.auth.secretKeys.clientSecret }}: {{ .Values.auth.credentials.clientSecret | b64enc }}
kind: Secret
metadata:
    name: hik8s-credentials
    namespace: {{ .Release.Namespace }}
{{- end }}
